version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: sa
      MB_DB_PASS: password1234
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    restart: always
